# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "centos7" do |node|
    node.vm.box = "centos7"
    node.vm.hostname = "zz"
    node.vm.network "private_network", ip: "192.168.33.10"
    node.vm.provision "shell", path: "centos-common.sh"
    node.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  end
end
