Vagrant.configure(2) do |config|
  config.vm.define "k8s-master" do |master|
    master.vm.box = "centos7"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.99.110"
    master.vm.provision "shell", path: "k8s-master.sh"
  end

  config.vm.define "k8s-node1" do |node|
    node.vm.box = "centos7"
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.99.111"
    node.vm.provision "shell", path: "k8s-node.sh"
    node.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  config.vm.define "k8s-node2" do |node|
    node.vm.box = "centos7"
    node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "192.168.99.112"
    node.vm.provision "shell", path: "k8s-node.sh"
    node.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end
